Sample codes for a simple grid problem , using random algorithms.

In [ ]:
# prompt: create a 3x3 grid on which I can perform value iteration

import numpy as np

class GridWorld:
    def __init__(self, size=3):
        self.size = size
        self.grid = np.zeros((size, size))
        # Example: Define some rewards (you can customize this)
        self.grid[0, 2] = 1  # Goal state
        self.grid[1, 1] = -1  # Obstacle or penalty

    def get_possible_actions(self, state):
        row, col = state
        actions = []
        if row > 0:
            actions.append("up")
        if row < self.size - 1:
            actions.append("down")
        if col > 0:
            actions.append("left")
        if col < self.size - 1:
            actions.append("right")
        return actions

    def get_next_state(self, state, action):
        row, col = state
        if action == "up":
            row -= 1
        elif action == "down":
            row += 1
        elif action == "left":
            col -= 1
        elif action == "right":
            col += 1
        return row, col

    def get_reward(self,state):
        return self.grid[state]

# Example usage
grid = GridWorld()
print(grid.grid)
print(grid.get_possible_actions((0,0)))
print(grid.get_next_state((0,0),"right"))
print(grid.get_reward((0,2)))


[[ 0.  0.  1.]
 [ 0. -1.  0.]
 [ 0.  0.  0.]]
['down', 'right']
(0, 1)
1.0


In [ ]:
# prompt: give me the probability for the state transition from current state to next state


In [ ]:
# prompt: Initialize V(s) belongs to R and pi(s) belongs to action arbitratily for all states

# Initialize V(s) and pi(s) arbitrarily for all states
import random

# Assuming a 3x3 grid world as an example
num_states = 9  # Number of states in the grid
num_actions = 4  # Number of possible actions (up, down, left, right)

# Initialize V(s) randomly
V = [0.0 for _ in range(num_states)]
V[2]=0
# Initialize pi(s) randomly
pi = [random.choice(grid.get_possible_actions((i/3,i%3))) for i in range(num_states)]

print("V(s):", V)
print("pi(s):", pi)


V(s): [0.0, 0.0, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
pi(s): ['down', 'down', 'up', 'right', 'left', 'left', 'right', 'right', 'left']


In [ ]:
#Policy Iteration

delta = 1e9
gamma = 0.9
i=0
count=0

while i<20000:
  i+=1
  while delta > 0.0001:
    delta = 0
    for s in range(num_states):
      v = V[s]
      a = pi[s]
      s_prime = grid.get_next_state((s//3,s%3),a)
      V[s] = grid.get_reward(s_prime) + gamma*V[s_prime[0]*3+s_prime[1]]
      delta = max(delta,abs(v-V[s]))
      #print(delta)
    #print(V)
    count+=1


  for s in range(num_states):
    q = []
    value=-100000
    for a in grid.get_possible_actions((s//3,s%3)):
      s_prime = grid.get_next_state((s//3,s%3),a)
      newvalue = grid.get_reward(s_prime) + gamma*V[s_prime[0]*3+s_prime[1]]
      if newvalue > value:
        value = newvalue
        pi[s] = a



In [ ]:
pi

['down', 'right', 'left', 'down', 'down', 'up', 'right', 'left', 'left']

In [ ]:
# Initialize V(s) and pi(s) arbitrarily for all states
import random

# Assuming a 3x3 grid world as an example
num_states = 9  # Number of states in the grid
num_actions = 4  # Number of possible actions (up, down, left, right)

# Initialize V(s) randomly
V = [0.0 for _ in range(num_states)]
V[2]=0
# Initialize pi(s) randomly
pi = [random.choice(grid.get_possible_actions((i/3,i%3))) for i in range(num_states)]

print("V(s):", V)
print("pi(s):", pi)

V(s): [0.0, 0.0, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
pi(s): ['down', 'up', 'left', 'right', 'down', 'down', 'right', 'right', 'left']


In [ ]:
#Value Iteration

delta = 1
gamma = 0.9
i=0
count=0

while i<20000 and delta>1e-10:
  print(i,' ',delta)
  i+=1
  delta = 0
  for s in range(num_states):
    v = V[s]
    for a in grid.get_possible_actions((s//3,s%3)):
      s_prime = grid.get_next_state((s//3,s%3),a)
      newvalue = grid.get_reward(s_prime) + gamma*V[s_prime[0]*3+s_prime[1]]
      if newvalue > V[s]:
        V[s] = newvalue
        pi[s] = a
    delta = max(delta,abs(v-V[s]))

0   1
1   1.81
2   1.4661
3   0.729
4   0.59049
5   0.47829690000000014
6   0.38742048900000015
7   0.31381059609000017
8   0.2541865828329004
9   0.20589113209464882
10   0.16677181699666566
11   0.13508517176729917
12   0.10941898913151249
13   0.08862938119652597
14   0.0717897987691849
15   0.05814973700304016
16   0.0471012869724623
17   0.038152042447694434
18   0.030903154382633247
19   0.025031555049932486
20   0.020275559590444914
21   0.016423203268260522
22   0.01330279464729145
23   0.010775263664305257
24   0.008727963568087915
25   0.007069650490151069
26   0.005726416897021913
27   0.004638397686588469
28   0.0037571021261362247
29   0.003043252722171097
30   0.002465034704957958
31   0.0019966781110163367
32   0.001617309269922984
33   0.0013100205086375993
34   0.001061116611996482
35   0.0008595044557173637
36   0.000696198609130505
37   0.0005639208733958512
38   0.0004567759074509681
39   0.00036998848503522197
40   0.00029969067287893836
41   0.0002427494450314427


In [ ]:
pi

['right', 'right', 'down', 'up', 'up', 'up', 'up', 'right', 'up']

In [ ]:
#monte carlo sampling
# Initialize V(s) and pi(s) arbitrarily for all states
import random

# Assuming a 3x3 grid world as an example
num_states = 9  # Number of states in the grid
num_actions = 4  # Number of possible actions (up, down, left, right)

# Initialize V(s) randomly
V = [0.0 for _ in range(num_states)]
N = [0 for _ in range(num_states)]


print("V(s):", V)




V(s): [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]


In [ ]:
#montecarlo simulation
import random

delta = 1
gamma = 0.9
i=0
count=0
goal = 2

while i<100000 and delta>1e-10:
  state =2
  while state==2:
    state = random.randint(0,8)


  stepstate = []
  stepaction = []
  reward = []
  while state != goal:
    x = state//3
    y = state%3
    action = random.choice(grid.get_possible_actions((x,y)))

    stepstate.append(state)
    stepaction.append(action)
    newx,newy = grid.get_next_state((x,y),action)
    reward.append(grid.get_reward((newx,newy)))
    state = newx*3+newy


  i+=1
  G=0
  for t in reversed(range(len(stepstate))):
    state = stepstate[t]
    action = stepaction[t]
    r = reward[t]
    G = gamma*G + r
    N[state]+=1
    V[state] = V[state] + (1/N[state])*(G-V[state])
V

[-0.5700572553930389,
 -0.34100960258853075,
 0.0,
 -0.9271435237106234,
 -0.5713963258581174,
 -0.3373495684315391,
 -0.8307158345720727,
 -0.9246368767413473,
 -0.5671859873368766]

In [ ]:
# prompt: write the code to generate the policy out of these value function from the above block for each state

# The policy is already generated within the Value Iteration and Policy Iteration loops.
# The 'pi' list contains the optimal action for each state after the loops complete.

# Value Iteration
#print("Optimal policy (Value Iteration):", pi)

# Policy Iteration
# The 'pi' list is updated in the policy iteration as well.  No need to recalculate, it's already done.
#print("Optimal policy (Policy Iteration):", pi)


# Monte Carlo
# The 'pi' list was not calculated in the monte carlo example, so we'll use the V values to make a policy.
# Find the best action for each state based on the estimated value function V.
pi_mc = []
for s in range(num_states):
    best_action = None
    best_value = -float('inf')
    for a in grid.get_possible_actions((s // 3, s % 3)):
        s_prime = grid.get_next_state((s // 3, s % 3), a)
        value = grid.get_reward(s_prime) + gamma * V[s_prime[0] * 3 + s_prime[1]]
        if value > best_value:
            best_value = value
            best_action = a
    pi_mc.append(best_action)

print("Optimal policy (Monte Carlo):", pi_mc)


Optimal policy (Monte Carlo): ['right', 'right', 'down', 'up', 'right', 'up', 'right', 'right', 'up']


In [ ]:
## Monte Carlo ES (Exploring Start)

import random

# Assuming a 3x3 grid world as an example
num_states = 9  # Number of states in the grid
num_actions = 4  # Number of possible actions (up, down, left, right)

# Initialize V(s) randomly
Q = [{'up':0.0,'down':0.0,'right':0.0,'left':0.0} for _ in range(num_states)]
N = [{'up':0,'down':0,'right':0,'left':0} for _ in range(num_states)]

# Initialize pi(s) randomly
pi = [random.choice(grid.get_possible_actions((i/3,i%3))) for i in range(num_states)]

print("Q(s,a):", Q)
print("pi(s):", pi)
print(N)


Q(s,a): [{'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}]
pi(s): ['down', 'left', 'down', 'right', 'right', 'up', 'up', 'left', 'left']
[{'up': 0, 'down': 0, 'right': 0, 'left': 0}, {'up': 0, 'down': 0, 'right': 0, 'left': 0}, {'up': 0, 'down': 0, 'right': 0, 'left': 0}, {'up': 0, 'down': 0, 'right': 0, 'left': 0}, {'up': 0, 'down': 0, 'right': 0, 'left': 0}, {'up': 0, 'down': 0, 'right': 0, 'left': 0}, {'up': 0, 'down': 0, 'right': 0, 'left': 0}, {'up': 0, 'down': 0, 'right': 0, 'left': 0}, {'up': 0, 'down': 0, 'right': 0, 'left': 0}]


In [ ]:
# THis apporach is the MC approach using monte carlo Non Exploring Start which is using a fixed policy and making modifications on top of that
#The other approach is the exploring start where there is a creation of randomized set of policies and choosing an action based on those policy and modifying our deployment policy ,
#working indirectly on the deployed policy

gamma = 0.9
i=0
goal = 2

while i<50000:
  state = random.randint(0,8)
  episodelength = 100

  stepstate = []
  stepaction = []
  reward = []
  while episodelength>0:
    x = state//3
    y = state%3
    action = pi[state]

    stepstate.append(state)
    if random.random()<0.1:
      action = random.choice(grid.get_possible_actions((x,y)))
      #print(action)
    stepaction.append(action)
    #print(action)
    newx,newy = grid.get_next_state((x,y),action)

    reward.append(grid.get_reward((newx,newy)))
    state = newx*3+newy
    episodelength-=1

  i+=1
  G=0
  for t in reversed(range(len(stepstate))):
    state = stepstate[t]
    action = stepaction[t]
    r = reward[t]
    G = gamma*G + r
    N[state][action]+=1
    Q[state][action] = Q[state][action] + (1/N[state][action])*(G-Q[state][action])
    for doable in grid.get_possible_actions((state//3,state%3)):
      if Q[state][doable] > Q[state][action]:
        action = doable
    pi[state] = action
Q

[{'up': 0.0,
  'down': 3.0873291487271093,
  'right': 4.1160280839509795,
  'left': 0.0},
 {'up': 0.0,
  'down': 2.4030393938297308,
  'right': 4.463866271674657,
  'left': 3.39162399198131},
 {'up': 0.0,
  'down': 3.844613713339005,
  'right': 0.0,
  'left': 3.8411760866612377},
 {'up': 3.6867222401464996,
  'down': 2.60471858266919,
  'right': 2.5896690819252086,
  'left': 0.0},
 {'up': 3.867757193768861,
  'down': 2.9791974712904405,
  'right': 3.8707209952482904,
  'left': 3.0097907793992538},
 {'up': 4.417950306349043,
  'down': 3.3746208892367036,
  'right': 0.0,
  'left': 2.378138606590601},
 {'up': 2.849055559040254,
  'down': 0.0,
  'right': 3.342645715110595,
  'left': 0.0},
 {'up': 2.567528310716744,
  'down': 0.0,
  'right': 3.659591281732555,
  'left': 2.8350562698196122},
 {'up': 3.9074742660294164,
  'down': 0.0,
  'right': 0.0,
  'left': 3.0139923108666546}]

In [ ]:
# Monte Carlo
# The 'pi' list was not calculated in the monte carlo example, so we'll use the V values to make a policy.
# Find the best action for each state based on the estimated value function V.
pi_mc = []
for s in range(num_states):
    best_action = None
    best_value = -float('inf')
    for a in grid.get_possible_actions((s // 3, s % 3)):
        value = Q[s][a]
        if value > best_value:
            best_value = value
            best_action = a
    pi_mc.append(best_action)

print("Optimal policy (Monte Carlo):", pi_mc)



Optimal policy (Monte Carlo): ['right', 'right', 'down', 'up', 'right', 'up', 'right', 'right', 'up']


Temporal Differen

Off Policy

Intuition
If
π
(
a
∣
s
)
>
b
(
a
∣
s
)
π(a∣s)>b(a∣s):
The target policy prefers this action more than the behavior policy.
The weight
W
W increases, giving more importance to this episode.
If
π
(
a
∣
s
)
<
b
(
a
∣
s
)
π(a∣s)<b(a∣s):
The behavior policy picked this action more often than the target policy would have.
The weight
W
W decreases, reducing the episode's influence.
If
W
=
0
W=0:
The behavior policy took an action that the target policy would never take.
The episode is ignored because it does not contribute valid learning.


In [ ]:
# prompt: create a 3x3 grid on which I can perform value iteration

import numpy as np

class GridWorld:
    def __init__(self, size=3):
        self.size = size
        self.grid = np.zeros((size, size))
        # Example: Define some rewards (you can customize this)
        self.grid[0, 2] = 1  # Goal state
        self.grid[1, 1] = -1  # Obstacle or penalty

    def get_possible_actions(self, state):
        row, col = state
        actions = []
        if row > 0:
            actions.append("up")
        if row < self.size - 1:
            actions.append("down")
        if col > 0:
            actions.append("left")
        if col < self.size - 1:
            actions.append("right")
        return actions

    def get_next_state(self, state, action):
        row, col = state
        if action == "up":
            row -= 1
        elif action == "down":
            row += 1
        elif action == "left":
            col -= 1
        elif action == "right":
            col += 1
        return row, col

    def get_reward(self,state):
        return self.grid[state]

# Example usage
grid = GridWorld()
print(grid.grid)
print(grid.get_possible_actions((0,0)))
print(grid.get_next_state((0,0),"right"))
print(grid.get_reward((0,2)))


[[ 0.  0.  1.]
 [ 0. -1.  0.]
 [ 0.  0.  0.]]
['down', 'right']
(0, 1)
1.0


In [ ]:

'''
Off Policy Monte carlo
if pi > b then more weightage since it is the good action
if b>pi then less weightage since it is the bad action

'''
import random

# Assuming a 3x3 grid world as an example
num_states = 9  # Number of states in the grid
num_actions = 4  # Number of possible actions (up, down, left, right)

# Initialize V(s) randomly
Q = [{'up':0.0,'down':0.0,'right':0.0,'left':0.0} for _ in range(num_states)]
W = 1
#winning strategy
pi = target_policy = {
    0: {"up": 0, "down": 0.05, "left": 0, "right": 0.95},  # (0,0) → mostly right
    1: {"up": 0, "down": 0.05, "left": 0.05, "right": 0.90},  # (0,1) → mostly right
    2: {"up": 0, "down": 0, "left": 0, "right": 1.00},  # (0,2) → goal state
    3: {"up": 0.90, "down": 0.05, "left": 0, "right": 0.05},  # (1,0) → mostly up
    4: {"up": 0.25, "down": 0.25, "left": 0.25, "right": 0.25},  # (1,1) → penalty (random)
    5: {"up": 0.90, "down": 0, "left": 0.05, "right": 0.05},  # (1,2) → mostly up
    6: {"up": 0.95, "down": 0, "left": 0, "right": 0.05},  # (2,0) → mostly up
    7: {"up": 0.90, "down": 0, "left": 0.05, "right": 0.05},  # (2,1) → mostly up
    8: {"up": 0.95, "down": 0, "left": 0.05, "right": 0},  # (2,2) → mostly left
}
# Initialize pi(s) randomly


print("Q(s,a):", Q)
print("pi(s):", pi)





Q(s,a): [{'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}]
pi(s): {0: {'up': 0, 'down': 0.05, 'left': 0, 'right': 0.95}, 1: {'up': 0, 'down': 0.05, 'left': 0.05, 'right': 0.9}, 2: {'up': 0, 'down': 0, 'left': 0, 'right': 1.0}, 3: {'up': 0.9, 'down': 0.05, 'left': 0, 'right': 0.05}, 4: {'up': 0.25, 'down': 0.25, 'left': 0.25, 'right': 0.25}, 5: {'up': 0.9, 'down': 0, 'left': 0.05, 'right': 0.05}, 6: {'up': 0.95, 'down': 0, 'left': 0, 'right': 0.05}, 7: {'up': 0.9, 'down': 0, 'left': 0.05, 'right': 0.05}, 8: {'up': 0.95, 'down': 0, 'left': 0.05, 'right': 0}}


In [ ]:
import numpy as np

def generate_behavior_policy(grid):
    """
    Generates a random behavior policy where each state has a probability distribution
    over four possible actions ('up', 'down', 'left', 'right').
    Returns:
        behavior_policy: A dictionary where each state (0-8) maps to an action probability dict.
    """
    behavior_policy = {}

    for i in range(num_states):
        actions = grid.get_possible_actions((i//3,i%3))
        action_probs = np.random.dirichlet(np.ones(len(actions)))  # Normalize to sum to 1
        behavior_policy[i] = dict(zip(actions, action_probs))

    return behavior_policy

# Example Usage
b_policy = generate_behavior_policy(grid)
actions, probabilities = zip(*b_policy[0].items())

print(actions)
print(probabilities)
print(random.choices(actions, probabilities)[0])
random.choices(actions, probabilities)

('down', 'right')
(0.11199894715459262, 0.8880010528454075)
right


['right']

In [ ]:
from os import WIFSTOPPED
# THis apporach is the MC approach using monte carlo Non Exploring Start which is using a fixed policy and making modifications on top of that
#The other approach is the exploring start where there is a creation of randomized set of policies and choosing an action based on those policy and modifying our deployment policy ,
#working indirectly on the deployed policy

gamma = 0.9
i=0
weightsum=0
goal =2
W = 1

while i<1000:
  state=goal
  while state==goal:
    state = random.randint(0,8)

  stepstate = []
  stepaction = []
  reward = []
  b_policy = generate_behavior_policy(grid)
  while state!=goal:
    x = state//3
    y = state%3

    actions, probabilities = zip(*b_policy[state].items())
    action = (random.choices(actions, probabilities)[0])
    random.choices(actions, probabilities)

    stepstate.append(state)

    stepaction.append(action)

    newx,newy = grid.get_next_state((x,y),action)

    reward.append(grid.get_reward((newx,newy)))
    state = newx*3+newy
    episodelength-=1
    if state == goal:
      break

  i+=1
  G=0
  print(stepstate)
  print(stepaction)
  print(reward)
  for t in reversed(range(len(stepstate))):
    state = stepstate[t]
    action = stepaction[t]
    r = reward[t]
    G = gamma*G + r
    weightsum+=W
    Q[state][action] = (W*G + Q[state][action]*(weightsum-W))/weightsum
    W *= pi[state][action]/b_policy[state][action]

  print(i)

In [ ]:
Q
# Monte Carlo
# The 'pi' list was not calculated in the monte carlo example, so we'll use the V values to make a policy.
# Find the best action for each state based on the estimated value function V.
pi_mc = []
for s in range(num_states):
    best_action = None
    best_value = -float('inf')
    for a in grid.get_possible_actions((s // 3, s % 3)):
        value = Q[s][a]
        if value > best_value:
            best_value = value
            best_action = a
    pi_mc.append(best_action)

print("Optimal policy (Monte Carlo):", pi_mc)
Q



Optimal policy (Monte Carlo): ['right', 'right', 'down', 'up', 'up', 'up', 'up', 'left', 'up']


[{'up': 0.0,
  'down': -6.849663001211501e-24,
  'right': 0.4668960295778518,
  'left': 0.0},
 {'up': 0.0,
  'down': -1.4711271465057875e-05,
  'right': 1.0,
  'left': 0.27933279809691325},
 {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0},
 {'up': -1.2146623757251116e-06,
  'down': -0.008595260029101466,
  'right': -0.00020800162185592418,
  'left': 0.0},
 {'up': 0.8715242468610542,
  'down': -0.1606273361408073,
  'right': 0.17984266898011136,
  'left': -3.1101529315471845e-06},
 {'up': 1.0,
  'down': 0.45579725011637034,
  'right': 0.0,
  'left': -0.05972919056164046},
 {'up': -0.0007978585885660013,
  'down': 0.0,
  'right': -0.09500397507794157,
  'left': 0.0},
 {'up': -0.1905938216112098,
  'down': 0.0,
  'right': -0.020746923101089734,
  'left': -0.0003439937440419606},
 {'up': 0.7020874115552237,
  'down': 0.0,
  'right': 0.0,
  'left': -0.06963937006243269}]

Temporal difference learning (TD(0))

In [ ]:
# prompt: create a 3x3 grid on which I can perform value iteration

import numpy as np

class GridWorld:
    def __init__(self, size=3):
        self.size = size
        self.grid = np.zeros((size, size))
        # Example: Define some rewards (you can customize this)
        self.grid[0, 2] = 1  # Goal state
        self.grid[1, 1] = -1  # Obstacle or penalty

    def get_possible_actions(self, state):
        row, col = state
        actions = []
        if row > 0:
            actions.append("up")
        if row < self.size - 1:
            actions.append("down")
        if col > 0:
            actions.append("left")
        if col < self.size - 1:
            actions.append("right")
        return actions

    def get_next_state(self, state, action):
        row, col = state
        if action == "up":
            row -= 1
        elif action == "down":
            row += 1
        elif action == "left":
            col -= 1
        elif action == "right":
            col += 1
        return row, col

    def get_reward(self,state):
        return self.grid[state]

# Example usage
grid = GridWorld()
print(grid.grid)
print(grid.get_possible_actions((0,0)))
print(grid.get_next_state((0,0),"right"))
print(grid.get_reward((0,2)))


[[ 0.  0.  1.]
 [ 0. -1.  0.]
 [ 0.  0.  0.]]
['down', 'right']
(0, 1)
1.0


In [ ]:
import random

# Assuming a 3x3 grid world as an example
num_states = 9  # Number of states in the grid
num_actions = 4  # Number of possible actions (up, down, left, right)

# Initialize V(s) randomly
V = [0 for _ in range(num_states)]
N = [0 for _ in range(num_states)]
W = 1
#winning strategy
pi = target_policy = {
    0: {"up": 0, "down": 0.5, "left": 0, "right": 0.5},  # (0,0) → mostly right
    1: {"up": 0, "down": 0.33, "left": 0.33, "right": 0.34},  # (0,1) → mostly right
    2: {"up": 0, "down": 0, "left": 0, "right": 1.00},  # (0,2) → goal state
    3: {"up": 0.34, "down": 0.33, "left": 0, "right": 0.33},  # (1,0) → mostly up
    4: {"up": 0.25, "down": 0.25, "left": 0.25, "right": 0.25},  # (1,1) → penalty (random)
    5: {"up": 0.33, "down": 0.34, "left": 0.33, "right": 0},  # (1,2) → mostly up
    6: {"up": 0.5, "down": 0, "left": 0, "right": 0.5},  # (2,0) → mostly up
    7: {"up": 0.33, "down": 0, "left": 0.33, "right": 0.34},  # (2,1) → mostly up
    8: {"up": 0.5, "down": 0, "left": 0.5, "right": 0},  # (2,2) → mostly left
}
# Initialize pi(s) randomly


print("Q(s,a):", V)
print("pi(s):", pi)

Q(s,a): [0, 0, 0, 0, 0, 0, 0, 0, 0]
pi(s): {0: {'up': 0, 'down': 0.5, 'left': 0, 'right': 0.5}, 1: {'up': 0, 'down': 0.33, 'left': 0.33, 'right': 0.34}, 2: {'up': 0, 'down': 0, 'left': 0, 'right': 1.0}, 3: {'up': 0.34, 'down': 0.33, 'left': 0, 'right': 0.33}, 4: {'up': 0.25, 'down': 0.25, 'left': 0.25, 'right': 0.25}, 5: {'up': 0.33, 'down': 0.34, 'left': 0.33, 'right': 0}, 6: {'up': 0.5, 'down': 0, 'left': 0, 'right': 0.5}, 7: {'up': 0.33, 'down': 0, 'left': 0.33, 'right': 0.34}, 8: {'up': 0.5, 'down': 0, 'left': 0.5, 'right': 0}}


In [ ]:
from os import WIFSTOPPED
# Temporal Difference learning


gamma = 0.9
i=0
weightsum=0
goal =2
W = 1

while i<100000:
  state=goal
  while state==goal:
    state = random.randint(0,8)
  #print(i,' ',state)
  i+=1
  while state!=goal:
    x = state//3
    y = state%3

    actions, probabilities = zip(*pi[state].items())
    action = (random.choices(actions, probabilities)[0])
    random.choices(actions, probabilities)
    N[state]+=1

    newx,newy = grid.get_next_state((x,y),action)

    reward = grid.get_reward((newx,newy))

    newstate = newx*3+newy
    V[state] = V[state] + (1/N[state])*(reward + gamma*V[newstate]-V[state])
    state = newstate

    if state == goal:
      break


In [ ]:
pi_td = []
for s in range(num_states):
    best_action = None
    best_value = -float('inf')
    for a in grid.get_possible_actions((s // 3, s % 3)):
        s_prime = grid.get_next_state((s // 3, s % 3), a)
        value = grid.get_reward(s_prime) + gamma * V[s_prime[0] * 3 + s_prime[1]]
        if value > best_value:
            best_value = value
            best_action = a
    pi_td.append(best_action)

print("Optimal policy (Monte Carlo):", pi_td)
V

Optimal policy (Monte Carlo): ['right', 'right', 'left', 'up', 'up', 'up', 'up', 'right', 'up']


[-0.45342391544426597,
 -0.24985498126499095,
 0,
 -0.7942998639469419,
 -0.461773568611392,
 -0.2752218658404506,
 -0.6989869536569517,
 -0.8029111772095301,
 -0.47257577931396855]

SARSA - TD Control (Q values come into play)[on policy since we decicde the next action based of our policy]

In [ ]:
import random

# Assuming a 3x3 grid world as an example
num_states = 9  # Number of states in the grid
num_actions = 4  # Number of possible actions (up, down, left, right)

# Initialize V(s) randomly
# Initialize V(s) randomly
Q = [{'up':0.0,'down':0.0,'right':0.0,'left':0.0} for _ in range(num_states)]
N = [0 for _ in range(num_states)]
W = 1
#winning strategy
pi = target_policy = {
    0: {"up": 0, "down": 0.5, "left": 0, "right": 0.5},  # (0,0) → mostly right
    1: {"up": 0, "down": 0.33, "left": 0.33, "right": 0.34},  # (0,1) → mostly right
    2: {"up": 0, "down": 0, "left": 0, "right": 1.00},  # (0,2) → goal state
    3: {"up": 0.34, "down": 0.33, "left": 0, "right": 0.33},  # (1,0) → mostly up
    4: {"up": 0.25, "down": 0.25, "left": 0.25, "right": 0.25},  # (1,1) → penalty (random)
    5: {"up": 0.33, "down": 0.34, "left": 0.33, "right": 0},  # (1,2) → mostly up
    6: {"up": 0.5, "down": 0, "left": 0, "right": 0.5},  # (2,0) → mostly up
    7: {"up": 0.33, "down": 0, "left": 0.33, "right": 0.34},  # (2,1) → mostly up
    8: {"up": 0.5, "down": 0, "left": 0.5, "right": 0},  # (2,2) → mostly left
}
# Initialize pi(s) randomly


print("Q(s,a):", Q)
print("pi(s):", pi)

Q(s,a): [{'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}]
pi(s): {0: {'up': 0, 'down': 0.5, 'left': 0, 'right': 0.5}, 1: {'up': 0, 'down': 0.33, 'left': 0.33, 'right': 0.34}, 2: {'up': 0, 'down': 0, 'left': 0, 'right': 1.0}, 3: {'up': 0.34, 'down': 0.33, 'left': 0, 'right': 0.33}, 4: {'up': 0.25, 'down': 0.25, 'left': 0.25, 'right': 0.25}, 5: {'up': 0.33, 'down': 0.34, 'left': 0.33, 'right': 0}, 6: {'up': 0.5, 'down': 0, 'left': 0, 'right': 0.5}, 7: {'up': 0.33, 'down': 0, 'left': 0.33, 'right': 0.34}, 8: {'up': 0.5, 'down': 0, 'left': 0.5, 'right': 0}}


In [ ]:
from os import WIFSTOPPED
# Temporal Difference learning


gamma = 0.9
i=0
weightsum=0
goal =2
W = 1

while i<100000:
  state=goal
  while state==goal:
    state = random.randint(0,8)
  #print(i,' ',state)
  i+=1
  while state!=goal:
    x = state//3
    y = state%3

    actions, probabilities = zip(*pi[state].items())
    action = (random.choices(actions, probabilities)[0])
    random.choices(actions, probabilities)
    N[state]+=1

    newx,newy = grid.get_next_state((x,y),action)

    reward = grid.get_reward((newx,newy))


    newstate = newx*3+newy
    newactions, probabilities = zip(*pi[newstate].items())
    newaction = (random.choices(newactions, probabilities)[0])

    Q[state][action] = Q[state][action] + (1/N[state])*(reward + gamma*Q[newstate][newaction]-Q[state][action])
    state = newstate

    if state == goal:
      break


In [ ]:
pi_mc = []
for s in range(num_states):
    best_action = None
    best_value = -float('inf')
    for a in grid.get_possible_actions((s // 3, s % 3)):
        value = Q[s][a]
        if value > best_value:
            best_value = value
            best_action = a
    pi_mc.append(best_action)

print("Optimal policy (Monte Carlo):", pi_mc)

Optimal policy (Monte Carlo): ['right', 'right', 'down', 'up', 'up', 'up', 'right', 'right', 'up']


Q-Learning (TD approach to the same but we are tweaking the future random action with the best next action ) so the same as above but now we take the best Q value of the next state [off policy - since we just take maximum value and ain't relying on policy]

In [ ]:
import random

# Assuming a 3x3 grid world as an example
num_states = 9  # Number of states in the grid
num_actions = 4  # Number of possible actions (up, down, left, right)

# Initialize V(s) randomly
# Initialize V(s) randomly
Q = [{'up':0.0,'down':0.0,'right':0.0,'left':0.0} for _ in range(num_states)]
N = [0 for _ in range(num_states)]
W = 1
#winning strategy
pi = target_policy = {
    0: {"up": 0, "down": 0.5, "left": 0, "right": 0.5},  # (0,0) → mostly right
    1: {"up": 0, "down": 0.33, "left": 0.33, "right": 0.34},  # (0,1) → mostly right
    2: {"up": 0, "down": 0, "left": 0, "right": 1.00},  # (0,2) → goal state
    3: {"up": 0.34, "down": 0.33, "left": 0, "right": 0.33},  # (1,0) → mostly up
    4: {"up": 0.25, "down": 0.25, "left": 0.25, "right": 0.25},  # (1,1) → penalty (random)
    5: {"up": 0.33, "down": 0.34, "left": 0.33, "right": 0},  # (1,2) → mostly up
    6: {"up": 0.5, "down": 0, "left": 0, "right": 0.5},  # (2,0) → mostly up
    7: {"up": 0.33, "down": 0, "left": 0.33, "right": 0.34},  # (2,1) → mostly up
    8: {"up": 0.5, "down": 0, "left": 0.5, "right": 0},  # (2,2) → mostly left
}
# Initialize pi(s) randomly


print("Q(s,a):", Q)
print("pi(s):", pi)

Q(s,a): [{'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}]
pi(s): {0: {'up': 0, 'down': 0.5, 'left': 0, 'right': 0.5}, 1: {'up': 0, 'down': 0.33, 'left': 0.33, 'right': 0.34}, 2: {'up': 0, 'down': 0, 'left': 0, 'right': 1.0}, 3: {'up': 0.34, 'down': 0.33, 'left': 0, 'right': 0.33}, 4: {'up': 0.25, 'down': 0.25, 'left': 0.25, 'right': 0.25}, 5: {'up': 0.33, 'down': 0.34, 'left': 0.33, 'right': 0}, 6: {'up': 0.5, 'down': 0, 'left': 0, 'right': 0.5}, 7: {'up': 0.33, 'down': 0, 'left': 0.33, 'right': 0.34}, 8: {'up': 0.5, 'down': 0, 'left': 0.5, 'right': 0}}


In [ ]:
from os import WIFSTOPPED
# Temporal Difference learning


gamma = 0.9
i=0
weightsum=0
goal =2
W = 1

while i<100000:
  state=goal
  while state==goal:
    state = random.randint(0,8)
  #print(i,' ',state)
  i+=1
  while state!=goal:
    x = state//3
    y = state%3

    actions, probabilities = zip(*pi[state].items())
    action = (random.choices(actions, probabilities)[0])
    random.choices(actions, probabilities)
    N[state]+=1

    newx,newy = grid.get_next_state((x,y),action)

    reward = grid.get_reward((newx,newy))


    newstate = newx*3+newy
    newaction = grid.get_possible_actions((newx,newy))[0]
    for a in grid.get_possible_actions((newx,newy)):
      if Q[newstate][a]>Q[newstate][newaction]:
        newaction = a


    Q[state][action] = Q[state][action] + (1/N[state])*(reward + gamma*Q[newstate][newaction]-Q[state][action])
    state = newstate

    if state == goal:
      break


In [ ]:
pi_mc = []
for s in range(num_states):
    best_action = None
    best_value = -float('inf')
    for a in grid.get_possible_actions((s // 3, s % 3)):
        value = Q[s][a]
        if value > best_value:
            best_value = value
            best_action = a
    pi_mc.append(best_action)

print("Optimal policy (Monte Carlo):", pi_mc)

Optimal policy (Monte Carlo): ['right', 'right', 'down', 'up', 'up', 'up', 'up', 'right', 'up']


In [ ]:
state = random.randint(0,8)
print(state)

1


Temporal Difference - n learning
The same shit but we are just making the computation depend on V(S (t+n)) rather than immediately on V(S (t))

In [1]:
# prompt: create a 3x3 grid on which I can perform value iteration

import numpy as np

class GridWorld:
    def __init__(self, size=3):
        self.size = size
        self.grid = np.zeros((size, size))
        # Example: Define some rewards (you can customize this)
        self.grid[0, 2] = 1  # Goal state
        self.grid[1, 1] = -1  # Obstacle or penalty

    def get_possible_actions(self, state):
        row, col = state
        actions = []
        if row > 0:
            actions.append("up")
        if row < self.size - 1:
            actions.append("down")
        if col > 0:
            actions.append("left")
        if col < self.size - 1:
            actions.append("right")
        return actions

    def get_next_state(self, state, action):
        row, col = state
        if action == "up":
            row -= 1
        elif action == "down":
            row += 1
        elif action == "left":
            col -= 1
        elif action == "right":
            col += 1
        return row, col

    def get_reward(self,state):
        return self.grid[state]

# Example usage
grid = GridWorld()
print(grid.grid)
print(grid.get_possible_actions((0,0)))
print(grid.get_next_state((0,0),"right"))
print(grid.get_reward((0,2)))


[[ 0.  0.  1.]
 [ 0. -1.  0.]
 [ 0.  0.  0.]]
['down', 'right']
(0, 1)
1.0


In [ ]:
import random

# Assuming a 3x3 grid world as an example
num_states = 9  # Number of states in the grid
num_actions = 4  # Number of possible actions (up, down, left, right)

# Initialize V(s) randomly
V = [0 for _ in range(num_states)]
N = [0 for _ in range(num_states)] # or use alpha
W = 1
#winning strategy
pi = target_policy = {
    0: {"down": 0.5, "right": 0.5},  # (0,0) → mostly right
    1: {"down": 0.33, "left": 0.33, "right": 0.34},  # (0,1) → mostly right
    2: {"right": 1.00},  # (0,2) → goal state
    3: {"up": 0.34, "down": 0.33, "right": 0.33},  # (1,0) → mostly up
    4: {"up": 0.25, "down": 0.25, "left": 0.25, "right": 0.25},  # (1,1) → penalty (random)
    5: {"up": 0.33, "down": 0.34, "left": 0.33},  # (1,2) → mostly up
    6: {"up": 0.5,  "right": 0.5},  # (2,0) → mostly up
    7: {"up": 0.33,  "left": 0.33, "right": 0.34},  # (2,1) → mostly up
    8: {"up": 0.5,  "left": 0.5},  # (2,2) → mostly left
}
# Initialize pi(s) randomly


print("V(s):", V)
print("pi(s):", pi)

V(s): [0, 0, 0, 0, 0, 0, 0, 0, 0]
pi(s): {0: {'down': 0.5, 'right': 0.5}, 1: {'down': 0.33, 'left': 0.33, 'right': 0.34}, 2: {'right': 1.0}, 3: {'up': 0.34, 'down': 0.33, 'right': 0.33}, 4: {'up': 0.25, 'down': 0.25, 'left': 0.25, 'right': 0.25}, 5: {'up': 0.33, 'down': 0.34, 'left': 0.33}, 6: {'up': 0.5, 'right': 0.5}, 7: {'up': 0.33, 'left': 0.33, 'right': 0.34}, 8: {'up': 0.5, 'left': 0.5}}


In [ ]:
episodes = 100000
goal = 2
n=3
gamma = 0.9

while episodes>0:
  episodes-=1
  state = goal
  nextactionlist = []

  rewardlist  = []

  while state==goal:
    state = random.randint(0,8)
  #print(state)
  nextstatelist = [state]
  t = 0
  T = 1e15
  tou = 0

  while tou!=T:
    if t<T:
      x = state//3
      y = state%3

      actions, probabilities = zip(*pi[state].items())
      action = (random.choices(actions, probabilities)[0])
      nextcoord = grid.get_next_state((x,y),action)
      #print(nextcoord)
      reward = grid.get_reward(nextcoord)
      rewardlist.append(reward)
      nextstate = nextcoord[0]*3 + nextcoord[1]
      nextstatelist.append(nextstate)
      nextactionlist.append(action)
      if nextstate == goal:
        T = t+1

    tou = t-n+1
    if tou>=0:
      G = 0
      for i in range(tou,min(tou+n,T)):
        G += gamma**(i-tou)*rewardlist[i]
      #print(nextstatelist)
      G += gamma**n*V[nextstatelist[min(tou+n,T)]]
      N[nextstatelist[tou]]+=1
      V[nextstatelist[tou]] = V[nextstatelist[tou]] + (1/N[nextstatelist[tou]])*(G-V[nextstatelist[tou]])
      state = nextstatelist[tou]
    t+=1

In [ ]:

pi_td = []
for s in range(num_states):
    best_action = None
    best_value = -float('inf')
    for a in grid.get_possible_actions((s // 3, s % 3)):
        s_prime = grid.get_next_state((s // 3, s % 3), a)
        value = grid.get_reward(s_prime) + gamma * V[s_prime[0] * 3 + s_prime[1]]
        if value > best_value:
            best_value = value
            best_action = a
    pi_td.append(best_action)

print("Optimal policy (Monte Carlo):", pi_td)
V

Optimal policy (Monte Carlo): ['right', 'right', 'left', 'up', 'up', 'up', 'up', 'right', 'up']


[np.float64(-0.6656856672664452),
 np.float64(-0.5874528805955271),
 0.0,
 np.float64(-0.7033405305981336),
 np.float64(-0.6732893269546492),
 np.float64(-0.5962057763156511),
 np.float64(-0.7350701764003185),
 np.float64(-0.7038256004279131),
 np.float64(-0.6676504255306188)]

SARSA for n step TD


In [142]:
import random

# Assuming a 3x3 grid world as an example
num_states = 9  # Number of states in the grid
num_actions = 4  # Number of possible actions (up, down, left, right)

# Initialize V(s) randomly
# Initialize V(s) randomly
Q = [{'up':0.0,'down':0.0,'right':0.0,'left':0.0} for _ in range(num_states)]
N = [{'up':0,'down':0,'right':0,'left':0} for _ in range(num_states)]

W = 1
#winning strategy
pi = target_policy = {
    0: {"down": 0.5, "right": 0.5},  # (0,0) → mostly right
    1: {"down": 0.33, "left": 0.33, "right": 0.34},  # (0,1) → mostly right
    2: {"right": 1.00},  # (0,2) → goal state
    3: {"up": 0.34, "down": 0.33, "right": 0.33},  # (1,0) → mostly up
    4: {"up": 0.25, "down": 0.25, "left": 0.25, "right": 0.25},  # (1,1) → penalty (random)
    5: {"up": 0.33, "down": 0.34, "left": 0.33},  # (1,2) → mostly up
    6: {"up": 0.5,  "right": 0.5},  # (2,0) → mostly up
    7: {"up": 0.33,  "left": 0.33, "right": 0.34},  # (2,1) → mostly up
    8: {"up": 0.5,  "left": 0.5},  # (2,2) → mostly left
}
# Initialize pi(s)


print("Q(s,a):", Q)
print("pi(s):", pi)

Q(s,a): [{'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}]
pi(s): {0: {'down': 0.5, 'right': 0.5}, 1: {'down': 0.33, 'left': 0.33, 'right': 0.34}, 2: {'right': 1.0}, 3: {'up': 0.34, 'down': 0.33, 'right': 0.33}, 4: {'up': 0.25, 'down': 0.25, 'left': 0.25, 'right': 0.25}, 5: {'up': 0.33, 'down': 0.34, 'left': 0.33}, 6: {'up': 0.5, 'right': 0.5}, 7: {'up': 0.33, 'left': 0.33, 'right': 0.34}, 8: {'up': 0.5, 'left': 0.5}}


In [16]:
episodes = 100000
goal = 2
n=2
gamma = 0.9

while episodes>0:
  episodes-=1
  state = goal
  nextactionlist = []
  print(episodes)
  rewardlist  = []

  while state==goal:
    state = random.randint(0,8)
  #print(state)
  nextstatelist = [state]
  t = 0
  T = 1e15
  tou = 0

  while tou!=T:
    if t<T:
      x = state//3
      y = state%3

      actions, probabilities = zip(*pi[state].items())
      action = (random.choices(actions, probabilities)[0])
      nextcoord = grid.get_next_state((x,y),action)
      #print(nextcoord)
      reward = grid.get_reward(nextcoord)
      rewardlist.append(reward)
      nextstate = nextcoord[0]*3 + nextcoord[1]
      nextstatelist.append(nextstate)
      nextactionlist.append(action)
      if nextstate == goal:
        T = t
      state = nextstate
    print(nextactionlist)
    print(nextstatelist)

    tou = t-n+1
    if tou>=0:
      G = 0
      for i in range(tou,min(tou+n,T)):
        G += gamma**(i-tou)*rewardlist[i]
      #print(nextstatelist)
      G += gamma**n**Q[nextstatelist[min(tou+n,T)-1]][nextactionlist[min(tou+n,T)-1]]
      print(nextstatelist[tou])
      print(nextactionlist[tou])
      N[nextstatelist[tou]][nextactionlist[tou]]+=1
      Q[nextstatelist[tou]][nextactionlist[tou]] = Q[nextstatelist[tou]][nextactionlist[tou]] + (1/N[nextstatelist[tou]][nextactionlist[tou]])*(G-Q[nextstatelist[tou]][nextactionlist[tou]])
    t+=1

Streaming output truncated to the last 5000 lines.
['up', 'up']
[8, 5, 2]
5
up
359
['up']
[7, 4]
['up', 'up']
[7, 4, 1]
7
up
['up', 'up', 'right']
[7, 4, 1, 2]
4
up
['up', 'up', 'right']
[7, 4, 1, 2]
1
right
358
['up']
[4, 1]
['up', 'right']
[4, 1, 2]
4
up
['up', 'right']
[4, 1, 2]
1
right
357
['up']
[8, 5]
['up', 'up']
[8, 5, 2]
8
up
['up', 'up']
[8, 5, 2]
5
up
356
['up']
[6, 3]
['up', 'right']
[6, 3, 4]
6
up
['up', 'right', 'up']
[6, 3, 4, 1]
3
right
['up', 'right', 'up', 'right']
[6, 3, 4, 1, 2]
4
up
['up', 'right', 'up', 'right']
[6, 3, 4, 1, 2]
1
right
355
['right']
[1, 2]
['right']
[1, 2]
1
right
354
['up']
[3, 0]
['up', 'right']
[3, 0, 1]
3
up
['up', 'right', 'right']
[3, 0, 1, 2]
0
right
['up', 'right', 'right']
[3, 0, 1, 2]
1
right
353
['up']
[5, 2]
['up']
[5, 2]
5
up
352
['down']
[4, 7]
['down', 'left']
[4, 7, 6]
4
down
['down', 'left', 'right']
[4, 7, 6, 7]
7
left
['down', 'left', 'right', 'left']
[4, 7, 6, 7, 6]
6
right
['down', 'left', 'right', 'left', 'right']
[4, 7, 6, 7

In [17]:
pi_mc = []
for s in range(num_states):
    best_action = None
    best_value = -float('inf')
    for a in grid.get_possible_actions((s // 3, s % 3)):
        value = Q[s][a]
        if value > best_value:
            best_value = value
            best_action = a
    pi_mc.append(best_action)

print("Optimal policy (Monte Carlo):", pi_mc)

Optimal policy (Monte Carlo): ['right', 'right', 'down', 'up', 'right', 'up', 'right', 'right', 'up']


In [ ]:
Q
print(grid.get_next_state((2,1),'left'))

(2, 0)


Off policy can also be done for the same thing .

This didn't work at my end , dunno what I've missed out 😭


In [125]:
import random

# Assuming a 3x3 grid world as an example
num_states = 9  # Number of states in the grid
num_actions = 4  # Number of possible actions (up, down, left, right)

# Initialize V(s) randomly
# Initialize V(s) randomly
Q = [{'up':0.0,'down':0.0,'right':0.0,'left':0.0} for _ in range(num_states)]
N = [0 for _ in range(num_states)]

W = 1
#winning strategy
pi = target_policy = {
    0: {"up": 0, "down": 0.05, "left": 0, "right": 0.95},  # (0,0) → mostly right
    1: {"up": 0, "down": 0.05, "left": 0.05, "right": 0.90},  # (0,1) → mostly right
    2: {"up": 0, "down": 0, "left": 0, "right": 1.00},  # (0,2) → goal state
    3: {"up": 0.90, "down": 0.05, "left": 0, "right": 0.05},  # (1,0) → mostly up
    4: {"up": 0.25, "down": 0.25, "left": 0.25, "right": 0.25},  # (1,1) → penalty (random)
    5: {"up": 0.90, "down": 0, "left": 0.05, "right": 0.05},  # (1,2) → mostly up
    6: {"up": 0.95, "down": 0, "left": 0, "right": 0.05},  # (2,0) → mostly up
    7: {"up": 0.90, "down": 0, "left": 0.05, "right": 0.05},  # (2,1) → mostly up
    8: {"up": 0.95, "down": 0, "left": 0.05, "right": 0},  # (2,2) → mostly left
}


print("Q(s,a):", Q)
print("pi(s):", pi)

import numpy as np

def generate_behavior_policy(grid):
    """
    Generates a random behavior policy where each state has a probability distribution
    over four possible actions ('up', 'down', 'left', 'right').
    Returns:
        behavior_policy: A dictionary where each state (0-8) maps to an action probability dict.
    """
    behavior_policy = {}

    for i in range(num_states):
        actions = grid.get_possible_actions((i//3,i%3))
        action_probs = np.random.dirichlet(np.ones(len(actions)))  # Normalize to sum to 1
        behavior_policy[i] = dict(zip(actions, action_probs))

    return behavior_policy

Q(s,a): [{'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}]
pi(s): {0: {'up': 0, 'down': 0.05, 'left': 0, 'right': 0.95}, 1: {'up': 0, 'down': 0.05, 'left': 0.05, 'right': 0.9}, 2: {'up': 0, 'down': 0, 'left': 0, 'right': 1.0}, 3: {'up': 0.9, 'down': 0.05, 'left': 0, 'right': 0.05}, 4: {'up': 0.25, 'down': 0.25, 'left': 0.25, 'right': 0.25}, 5: {'up': 0.9, 'down': 0, 'left': 0.05, 'right': 0.05}, 6: {'up': 0.95, 'down': 0, 'left': 0, 'right': 0.05}, 7: {'up': 0.9, 'down': 0, 'left': 0.05, 'right': 0.05}, 8: {'up': 0.95, 'down': 0, 'left': 0.05, 'right': 0}}


In [133]:
episodes = 100000
goal = 2
n=2
gamma = 0.9
alpha = 0.001

while episodes>0:
  b = generate_behavior_policy(grid)
  episodes-=1
  state = goal
  nextactionlist = []
  print(episodes)
  rewardlist  = []

  while state==goal:
    state = random.randint(0,8)
  #print(state)
  nextstatelist = [state]
  t = 0
  T = 1e15
  tou = 0

  while tou!=T:
    print("T  and tou= ",T," tou = ",tou)
    if t<T:
      x = state//3
      y = state%3

      actions, probabilities = zip(*b[state].items())
      action = (random.choices(actions, probabilities)[0])
      nextcoord = grid.get_next_state((x,y),action)
      #print(nextcoord)
      reward = grid.get_reward(nextcoord)
      rewardlist.append(reward)
      nextstate = nextcoord[0]*3 + nextcoord[1]
      nextstatelist.append(nextstate)
      nextactionlist.append(action)
      if nextstate == goal:
        T = t
      state = nextstate
    #print(nextactionlist)
    #print(nextstatelist)

    tou = t-n+1
    print("STATE:",nextstatelist[tou])
    print("ACTION:",nextactionlist[tou])
    if tou>=0:
      print(tou)
      G = 0
      p = 1.0
      for i in range(tou,min(tou+n,T)):
        #p *= pi[nextstatelist[i]][nextactionlist[i]]/b[nextstatelist[i]][nextactionlist[i]]
        G += gamma**(i-tou)*rewardlist[i]
      print("EXPLORATIONS ARE:")
      for i in range(tou,min(tou+n,T+1)):
        print(nextstatelist[i],' : ',nextactionlist[i])
        p *= pi[nextstatelist[i]][nextactionlist[i]]/b[nextstatelist[i]][nextactionlist[i]]

      G += gamma**n*Q[nextstatelist[min(tou+n,T)-1]][nextactionlist[min(tou+n,T)-1]]

      print(len(nextactionlist)," , ",tou)

      print(p)
      N[nextstatelist[tou]]+=1
      Q[nextstatelist[tou]][nextactionlist[tou]] = Q[nextstatelist[tou]][nextactionlist[tou]] + alpha*p*(G-Q[nextstatelist[tou]][nextactionlist[tou]])
    t+=1
  print(nextactionlist)
  print(nextstatelist)

Streaming output truncated to the last 5000 lines.
3  :  down
21  ,  19
0.06147868622715468
T  and tou=  1000000000000000.0  tou =  19
STATE: 3
ACTION: down
20
EXPLORATIONS ARE:
3  :  down
6  :  up
22  ,  20
0.06147868622715468
T  and tou=  1000000000000000.0  tou =  20
STATE: 6
ACTION: up
21
EXPLORATIONS ARE:
6  :  up
3  :  down
23  ,  21
0.06147868622715468
T  and tou=  1000000000000000.0  tou =  21
STATE: 3
ACTION: down
22
EXPLORATIONS ARE:
3  :  down
6  :  up
24  ,  22
0.06147868622715468
T  and tou=  1000000000000000.0  tou =  22
STATE: 6
ACTION: up
23
EXPLORATIONS ARE:
6  :  up
3  :  down
25  ,  23
0.06147868622715468
T  and tou=  1000000000000000.0  tou =  23
STATE: 3
ACTION: down
24
EXPLORATIONS ARE:
3  :  down
6  :  up
26  ,  24
0.06147868622715468
T  and tou=  1000000000000000.0  tou =  24
STATE: 6
ACTION: up
25
EXPLORATIONS ARE:
6  :  up
3  :  down
27  ,  25
0.06147868622715468
T  and tou=  1000000000000000.0  tou =  25
STATE: 3
ACTION: down
26
EXPLORATIONS ARE:
3  :  down
6

In [134]:
pi_mc = []
for s in range(num_states):
    best_action = None
    best_value = -float('inf')
    for a in grid.get_possible_actions((s // 3, s % 3)):
        value = Q[s][a]
        if value > best_value:
            best_value = value
            best_action = a
    pi_mc.append(best_action)

print("Optimal policy (Monte Carlo):", pi_mc)
Q

Optimal policy (Monte Carlo): ['down', 'right', 'down', 'up', 'left', 'down', 'up', 'left', 'up']


[{'up': 0.0,
  'down': np.float64(-0.36399649101802967),
  'right': np.float64(-0.41931941985822485),
  'left': 0.0},
 {'up': 0.0,
  'down': np.float64(-1.6854699141563307),
  'right': np.float64(-0.30550141514446744),
  'left': np.float64(-0.3337581208761334)},
 {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0},
 {'up': np.float64(-0.3213868736057679),
  'down': np.float64(-0.3514443417996058),
  'right': np.float64(-1.6926848919370354),
  'left': 0.0},
 {'up': np.float64(-0.4168350135379984),
  'down': np.float64(-2.0420512643981037),
  'right': np.float64(-0.5963092246254881),
  'left': np.float64(-0.3423952579648776)},
 {'up': np.float64(-0.4255352285930716),
  'down': np.float64(0.0),
  'right': 0.0,
  'left': np.float64(-1.7071751233216759)},
 {'up': np.float64(-0.35715349938082025),
  'down': 0.0,
  'right': np.float64(-2.0811443475497935),
  'left': 0.0},
 {'up': np.float64(-1.612539258562957),
  'down': 0.0,
  'right': np.float64(-0.5016763212820271),
  'left': np.float64(-0

THE ABOVE DIDN"T WORK FOR SOME REASON :(

-----------------------------------------

n step Tree Backup for estimating Q

Tree backup estimating  n-step

In [148]:
# prompt: create a 3x3 grid on which I can perform value iteration

import numpy as np

class GridWorld:
    def __init__(self, size=3):
        self.size = size
        self.grid = np.zeros((size, size))
        # Example: Define some rewards (you can customize this)
        self.grid[0, 2] = 1  # Goal state
        self.grid[1, 1] = -1  # Obstacle or penalty

    def get_possible_actions(self, state):
        row, col = state
        actions = []
        if row > 0:
            actions.append("up")
        if row < self.size - 1:
            actions.append("down")
        if col > 0:
            actions.append("left")
        if col < self.size - 1:
            actions.append("right")
        return actions

    def get_next_state(self, state, action):
        row, col = state
        if action == "up":
            row -= 1
        elif action == "down":
            row += 1
        elif action == "left":
            col -= 1
        elif action == "right":
            col += 1
        return row, col

    def get_reward(self,state):
        return self.grid[state]

# Example usage
grid = GridWorld()
print(grid.grid)
print(grid.get_possible_actions((0,0)))
print(grid.get_next_state((0,0),"right"))
print(grid.get_reward((0,2)))


[[ 0.  0.  1.]
 [ 0. -1.  0.]
 [ 0.  0.  0.]]
['down', 'right']
(0, 1)
1.0


In [149]:
import random

# Assuming a 3x3 grid world as an example
num_states = 9  # Number of states in the grid
num_actions = 4  # Number of possible actions (up, down, left, right)

# Initialize V(s) randomly
# Initialize V(s) randomly
Q = [{'up':0.0,'down':0.0,'right':0.0,'left':0.0} for _ in range(num_states)]
N = [{'up':0,'down':0,'right':0,'left':0} for _ in range(num_states)]

W = 1
#winning strategy
pi = target_policy = {
    0: {"down": 0.5, "right": 0.5},  # (0,0) → mostly right
    1: {"down": 0.33, "left": 0.33, "right": 0.34},  # (0,1) → mostly right
    2: {"right": 1.00},  # (0,2) → goal state
    3: {"up": 0.34, "down": 0.33, "right": 0.33},  # (1,0) → mostly up
    4: {"up": 0.25, "down": 0.25, "left": 0.25, "right": 0.25},  # (1,1) → penalty (random)
    5: {"up": 0.33, "down": 0.34, "left": 0.33},  # (1,2) → mostly up
    6: {"up": 0.5,  "right": 0.5},  # (2,0) → mostly up
    7: {"up": 0.33,  "left": 0.33, "right": 0.34},  # (2,1) → mostly up
    8: {"up": 0.5,  "left": 0.5},  # (2,2) → mostly left
}
# Initialize pi(s)


print("Q(s,a):", Q)
print("pi(s):", pi)

Q(s,a): [{'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}]
pi(s): {0: {'down': 0.5, 'right': 0.5}, 1: {'down': 0.33, 'left': 0.33, 'right': 0.34}, 2: {'right': 1.0}, 3: {'up': 0.34, 'down': 0.33, 'right': 0.33}, 4: {'up': 0.25, 'down': 0.25, 'left': 0.25, 'right': 0.25}, 5: {'up': 0.33, 'down': 0.34, 'left': 0.33}, 6: {'up': 0.5, 'right': 0.5}, 7: {'up': 0.33, 'left': 0.33, 'right': 0.34}, 8: {'up': 0.5, 'left': 0.5}}


In [ ]:
episodes = 100000
goal = 2
n=2
gamma = 0.9

while episodes>0:
  episodes-=1
  state = goal
  nextactionlist = []
  print(episodes)
  rewardlist  = []

  while state==goal:
    state = random.randint(0,8)
  #print(state)
  nextstatelist = [state]
  t = 0
  T = 1e15
  tou = 0

  while tou!=T:
    if t<T:
      x = state//3
      y = state%3

      actions, probabilities = zip(*pi[state].items())
      action = (random.choices(actions, probabilities)[0])
      nextcoord = grid.get_next_state((x,y),action)
      #print(nextcoord)
      reward = grid.get_reward(nextcoord)
      rewardlist.append(reward)
      nextstate = nextcoord[0]*3 + nextcoord[1]
      nextstatelist.append(nextstate)
      nextactionlist.append(action)
      if nextstate == goal:
        T = t
      state = nextstate


    tou = t-n+1
    if tou>=0:
      G = 0
      if t+1>=T:
        G = rewardlist[t]
      else:
        # you have to make it recursiv eand I didn't feel like doing it at the moment . The algorithm code is in 175pg
        #the algorithm uses expected SARSA but recursively goes down on the specific action path chosen
      for i in range(tou,min(tou+n,T)):
        G += gamma**(i-tou)*rewardlist[i]
      #print(nextstatelist)
      G += gamma**n**Q[nextstatelist[min(tou+n,T)-1]][nextactionlist[min(tou+n,T)-1]]
      N[nextstatelist[tou]][nextactionlist[tou]]+=1
      Q[nextstatelist[tou]][nextactionlist[tou]] = Q[nextstatelist[tou]][nextactionlist[tou]] + (1/N[nextstatelist[tou]][nextactionlist[tou]])*(G-Q[nextstatelist[tou]][nextactionlist[tou]])
    t+=1

------------------------------------------------------------------------------------

In [ ]:
import random

# Assuming a 3x3 grid world as an example
num_states = 9  # Number of states in the grid
num_actions = 4  # Number of possible actions (up, down, left, right)

# Initialize V(s) randomly
V = [0 for _ in range(num_states)]
N = [0 for _ in range(num_states)] # or use alpha
W = 1
#winning strategy
pi = target_policy = {
    0: {"down": 0.5, "right": 0.5},  # (0,0) → mostly right
    1: {"down": 0.33, "left": 0.33, "right": 0.34},  # (0,1) → mostly right
    2: {"right": 1.00},  # (0,2) → goal state
    3: {"up": 0.34, "down": 0.33, "right": 0.33},  # (1,0) → mostly up
    4: {"up": 0.25, "down": 0.25, "left": 0.25, "right": 0.25},  # (1,1) → penalty (random)
    5: {"up": 0.33, "down": 0.34, "left": 0.33},  # (1,2) → mostly up
    6: {"up": 0.5,  "right": 0.5},  # (2,0) → mostly up
    7: {"up": 0.33,  "left": 0.33, "right": 0.34},  # (2,1) → mostly up
    8: {"up": 0.5,  "left": 0.5},  # (2,2) → mostly left
}
# Initialize pi(s) randomly


print("V(s):", V)
print("pi(s):", pi)

In [61]:
import matplotlib.pyplot as plt
import numpy as np

TARGET_VALUE = 100
PR_H = 0.4
GAMMA = 1


def states():
    for s in range(1, TARGET_VALUE):
        yield s


def step(action, state, V):
    action_return = 0

    # success
    sp = min(state + action, TARGET_VALUE)
    action_return += PR_H * ((sp == TARGET_VALUE) + GAMMA * V[sp])

    # fail
    sp = max(state - action, 0)
    action_return += (1 - PR_H) * (GAMMA * V[sp])

    return action_return


def value_iteration(file_name='figure_4_3.png'):
    V = np.zeros(TARGET_VALUE + 1)
    pi = np.empty(TARGET_VALUE + 1, dtype=int)
    pi[0] = 0
    pi[TARGET_VALUE] = 0

    theta = 1e-9
    delta = 1
    iteration = 0
    value_function_history = []

    while delta > theta:
        iteration += 1
        delta = 0
        value_function_history.append(V.copy())

        for s in states():
            v_old = V[s]
            action_returns = []
            for a in range(1, min(s, TARGET_VALUE - s) + 1):
                action_return = step(a, s, V)
                action_returns.append(action_return)
            V[s] = max(action_returns)
            delta = max(delta, abs(v_old - V[s]))

        print("Policy iteration {} completed, delta {}".format(iteration, delta))

    value_function_history.append(V.copy())

    for s in states():
        action_returns = []
        actions = np.arange(min(s, TARGET_VALUE - s) + 1)
        for a in actions:
            action_return = step(a, s, V)
            action_returns.append(action_return)

        # exclude first index and round to obtain the same figure as in the book
        # the idea is taken from :
        # https://github.com/ShangtongZhang/reinforcement-learning-an-introduction/blob/master/chapter04/gamblers_problem.py
        pi[s] = actions[np.argmax(np.round(action_returns[1:], 5)) + 1]

    plt.figure(figsize=(10, 20))

    plt.subplot(2, 1, 1)
    for sweep, state_value in enumerate(value_function_history[:10]):
        plt.plot(state_value[1:100], label='sweep {}'.format(sweep), linewidth='0.9')

    if len(value_function_history)>10:
        plt.plot(value_function_history[-1][1:100], label='sweep {}'.format(len(value_function_history)-1))

    plt.title('Ph={}'.format(PR_H))
    plt.xlabel('Capital')
    plt.ylabel('Value estimates')
    plt.legend(loc='best')


    plt.subplot(2, 1, 2)
    plt.bar(np.arange(TARGET_VALUE + 1), pi)
    plt.xlabel('Capital')
    plt.ylabel('Final policy (stake)')

    plt.close()


def solve_gamblers_problem(p=0.4, file_name='figure_4_3.png'):
    global PR_H
    PR_H = p
    value_iteration(file_name)

In [ ]:
solve_gamblers_problem()


Policy iteration 1 completed, delta 0.9533440000000001
Policy iteration 2 completed, delta 0.3688960000000001
Policy iteration 3 completed, delta 0.13926400000000005
Policy iteration 4 completed, delta 0.05570560000000002
Policy iteration 5 completed, delta 0.02228224000000001
Policy iteration 6 completed, delta 0.008912896000000003
Policy iteration 7 completed, delta 0.0016384000000000008
Policy iteration 8 completed, delta 0.0003932160000000005
Policy iteration 9 completed, delta 7.602595430399994e-05
Policy iteration 10 completed, delta 3.041038172160032e-05
Policy iteration 11 completed, delta 2.6418075402233343e-06
Policy iteration 12 completed, delta 9.045549017728909e-07
Policy iteration 13 completed, delta 7.815354352569415e-08
Policy iteration 14 completed, delta 1.8756850440893036e-08
Policy iteration 15 completed, delta 5.230363003816407e-09
Policy iteration 16 completed, delta 1.869841788348925e-09
Policy iteration 17 completed, delta 7.479367151660976e-10


In [147]:
import numpy as np

class GridWorld:
    def __init__(self, size=3):
        self.size = size
        self.grid = np.zeros((size, size))
        # Define rewards
        self.grid[0, 2] = 1  # Goal state
        self.grid[1, 1] = -1  # Penalty state

    def get_possible_actions(self, state):
        row, col = state
        actions = []
        if row > 0:
            actions.append("up")
        if row < self.size - 1:
            actions.append("down")
        if col > 0:
            actions.append("left")
        if col < self.size - 1:
            actions.append("right")
        return actions

    def get_next_state(self, state, action):
        row, col = state
        if action == "up":
            row = max(0, row - 1)
        elif action == "down":
            row = min(self.size - 1, row + 1)
        elif action == "left":
            col = max(0, col - 1)
        elif action == "right":
            col = min(self.size - 1, col + 1)
        return row, col

    def get_reward(self, state):
        return self.grid[state]

class NStepSARSA:
    def __init__(self, env, n=3, alpha=0.1, gamma=0.9, epsilon=0.1):
        self.env = env
        self.n = n  # n-step parameter
        self.alpha = alpha  # learning rate
        self.gamma = gamma  # discount factor
        self.epsilon = epsilon  # exploration rate

        # Initialize Q-values
        self.actions = ["up", "down", "left", "right"]
        self.Q = np.zeros((env.size, env.size, len(self.actions)))

    def get_action_index(self, action):
        return self.actions.index(action)

    def epsilon_greedy_policy(self, state):
        if np.random.random() < self.epsilon:
            possible_actions = self.env.get_possible_actions(state)
            return np.random.choice(possible_actions)
        else:
            # Get Q-values for current state
            q_values = self.Q[state[0], state[1]]
            # Find best action among possible actions
            possible_actions = self.env.get_possible_actions(state)
            best_action_idx = np.argmax([q_values[self.get_action_index(a)]
                                       for a in possible_actions])
            return possible_actions[best_action_idx]

    def behavior_policy(self, state):
        # Random policy for off-policy learning
        possible_actions = self.env.get_possible_actions(state)
        return np.random.choice(possible_actions)

    def train(self, episodes=100000):
        for episode in range(episodes):
            # Initialize episode
            state = (1, 0)  # Starting position
            T = float('inf')
            t = 0
            states = [state]
            actions = []
            rewards = [0]

            while True:
                if t < T:
                    # Take action using behavior policy
                    action = self.behavior_policy(state)
                    actions.append(action)
                    next_state = self.env.get_next_state(state, action)
                    reward = self.env.get_reward(next_state)

                    states.append(next_state)
                    rewards.append(reward)

                    if reward == 1:  # Reached goal
                        T = t + 1
                    else:
                        state = next_state

                tau = t - self.n + 1  # State to update

                if tau >= 0:
                    # Calculate n-step return
                    G = 0
                    for i in range(tau + 1, min(tau + self.n + 1, T + 1)):
                        G += (self.gamma ** (i - tau - 1)) * rewards[i]

                    if tau + self.n < T:
                        state_n = states[tau + self.n]
                        action_n = self.epsilon_greedy_policy(state_n)
                        G += (self.gamma ** self.n) * self.Q[state_n[0], state_n[1],
                                                            self.get_action_index(action_n)]

                    # Update Q-value
                    state_tau = states[tau]
                    action_tau = actions[tau]
                    action_idx = self.get_action_index(action_tau)
                    self.Q[state_tau[0], state_tau[1], action_idx] += \
                        self.alpha * (G - self.Q[state_tau[0], state_tau[1], action_idx])

                t += 1
                if tau == T - 1:
                    break

    def print_policy(self):
        action_symbols = {"up": "↑", "down": "↓", "left": "←", "right": "→"}
        for i in range(self.env.size):
            row = ""
            for j in range(self.env.size):
                state = (i, j)
                if self.env.grid[i, j] == 1:
                    row += " G "
                elif self.env.grid[i, j] == -1:
                    row += " X "
                else:
                    action = self.epsilon_greedy_policy(state)
                    row += f" {action_symbols[action]} "
            print(row)

# Run the example
env = GridWorld()
agent = NStepSARSA(env, n=3)
agent.train(episodes=1000)

# Print results
print("Reward Grid:")
print(env.grid)
print("\nLearned Policy:")
agent.print_policy()
print("\nQ-values for starting position (1,0):")
print(Q)

Reward Grid:
[[ 0.  0.  1.]
 [ 0. -1.  0.]
 [ 0.  0.  0.]]

Learned Policy:
 →  →  G 
 ↑  X  ↑ 
 →  ←  ← 

Q-values for starting position (1,0):
[{'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}, {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}]


In [146]:
pi_mc = []
for s in range(num_states):
    best_action = None
    best_value = -float('inf')
    for a in grid.get_possible_actions((s // 3, s % 3)):
        value = Q[s][a]
        if value > best_value:
            best_value = value
            best_action = a
    pi_mc.append(best_action)

print("Optimal policy (Monte Carlo):", pi_mc)
Q

Optimal policy (Monte Carlo): ['down', 'down', 'down', 'up', 'up', 'up', 'up', 'up', 'up']


[{'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0},
 {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0},
 {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0},
 {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0},
 {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0},
 {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0},
 {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0},
 {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0},
 {'up': 0.0, 'down': 0.0, 'right': 0.0, 'left': 0.0}]